server:
  port: 8000

spring:
  application:
    name: exchange-service

  datasource:
    url: jdbc:postgresql://localhost:5432/exchange_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

management:
  tracing:
    sampling:
      probability: 1.0 # 1.0 == 100%

    export:
      zipkin:
        endpoint: ${MANAGEMENT_TRACING_EXPORT_ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

springdoc:
  api-docs:
    path: /exchange-service/v3/api-docs
  swagger-ui:
    url: /exchange-service/v3/api-docs
  override-server-url: true