server:
  port: 8761 # default: 8671

spring:
  application:
    name: naming-server

management:
  tracing:
    sampling:
      probability: 1.0 # 1.0 == 100%

    export:
      zipkin:
        endpoint: ${MANAGEMENT_TRACING_EXPORT_ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false # tenta se registrar em si mesmo
